# Project information
site_name: Va.Si.Li-Lab Docs
site_url: https://texttechnologylab.github.io/Va.Si.Li-Lab/
site_description: >-
  Documentation for Va.Si.Li-Lab


# Repository
repo_url: https://github.com/texttechnologylab/Va.Si.Li-Lab
repo_name: texttechnologylab/Va.Si.Li-Lab


# Page tree
nav:
    - Home: index.md
    - Getting Started:
        - Setting Up Va.Si.Li-Lab: setting_up.md
        - Meta Avatars: meta_avatars.md
        - Player Controller: player_controller.md

    - Other Functions:
        - Replay Experiment: replay.md
        - Bots: bots.md

    - Server Structure: 
        - Ubiq Server: ./server/ubiq_server.md
        - Python Data Logger: ./server/python_data_logger.md
        - Java Service: ./server/java_service.md
        - MongoDB: ./server/mongodb.md

    - Projects:
        - Digitell: ./projects/digitell.md
        - ViCom: ./projects/vicom.md
        - New Data Spaces: ./projects/faces.md

    - Publications: publications.md


# Configuration
theme:
    name: material
    logo: images/logo/29729890.png
    icon:
        repo: fontawesome/brands/github
    # Light/Darkmode
    palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

    features:
        # - content.code.annotate
        - content.code.copy
        - content.code.annotate
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.instant.progress
        # - navigation.sections
        - navigation.expand
        - navigation.tracking
        - search.highlight
        # - search.share
        - search.suggest


# Additional configuration
extra:
    homepage: https://texttechnologylab.github.io/Va.Si.Li-Lab/
    status:
        new: Recently added
        deprecated: Deprecated
    social:
        - icon: fontawesome/solid/house
          link: https://www.texttechnologylab.org/
        - icon: fontawesome/brands/github
          link: https://github.com/texttechnologylab
        - icon: fontawesome/brands/x-twitter
          link: https://twitter.com/ttlab_ffm
        - icon: fontawesome/brands/researchgate
          link: https://www.researchgate.net/lab/Text-Technology-Lab-TTLab-Alexander-Mehler
        - icon: fontawesome/brands/youtube
          link: https://www.youtube.com/channel/UCST6Bz8tydqR-VOnihevKtg

plugins:
    - git-revision-date-localized:
          enable_creation_date: true
    - search
    #- git-authors
    #- git-committers:
    #    repository: texttechnologylab/Va.Si.Li-Lab
    #    branch: main


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences