site_name: Va.Si.Li-Labs Docs
nav:
    - Home: index.md
    - Getting Started:
        - Setting Up Va.Si.Li-Lab: setting_up.md
        
    - Advanced:
        - Meta Avatars: meta_avatars.md
        - Server Structure: 
            - Ubiq Server: ubiq_server.md
            - Python Data Logger: python_data_loggert.md
            - Java Service: java_service.md
            - MongoDB: mongodb.md
    
    - Projects:
        - Digitell: digitell.md
        - ViCom: vicom.md
theme:
    name: material
